import type { Player, Match } from './types'

export function generateSingleEliminationMatches(
  tournamentId: string,
  players: Player[]
): Omit<Match, 'id' | 'player1' | 'player2'>[] {
  const rounds = Math.ceil(Math.log2(players.length))
  const slots = Math.pow(2, rounds)
  const matches: Omit<Match, 'id' | 'player1' | 'player2'>[] = []

  for (let pos = 0; pos < slots / 2; pos++) {
    const p1 = players[pos * 2] ?? null
    const p2 = players[pos * 2 + 1] ?? null
    matches.push({
      tournament_id: tournamentId,
      round: 1,
      position: pos,
      player1_id: p1?.id ?? null,
      player2_id: p2?.id ?? null,
      score1: null,
      score2: null,
      winner_id: p2 === null && p1 ? p1.id : null,
      status: p2 === null && p1 ? 'completed' : 'pending',
    })
  }

  for (let round = 2; round <= rounds; round++) {
    const count = slots / Math.pow(2, round)
    for (let pos = 0; pos < count; pos++) {
      matches.push({
        tournament_id: tournamentId,
        round,
        position: pos,
        player1_id: null,
        player2_id: null,
        score1: null,
        score2: null,
        winner_id: null,
        status: 'pending',
      })
    }
  }

  return matches
}

export function generateRoundRobinMatches(
  tournamentId: string,
  players: Player[]
): Omit<Match, 'id' | 'player1' | 'player2'>[] {
  const matches: Omit<Match, 'id' | 'player1' | 'player2'>[] = []
  let position = 0
  for (let i = 0; i < players.length; i++) {
    for (let j = i + 1; j < players.length; j++) {
      matches.push({
        tournament_id: tournamentId,
        round: 1,
        position: position++,
        player1_id: players[i].id,
        player2_id: players[j].id,
        score1: null,
        score2: null,
        winner_id: null,
        status: 'pending',
      })
    }
  }
  return matches
}

// Generates round 1 only. Subsequent rounds are generated by generateAmericanoNextRound.
// Pairing: seed 1 & 3 (team 1) vs seed 2 & 4 (team 2) per court.
export function generateAmericanoMatches(
  tournamentId: string,
  players: Player[]
): Omit<Match, 'id' | 'player1' | 'player2' | 'player3' | 'player4'>[] {
  return pairAmericanoRound(tournamentId, 1, players)
}

// Generates the next round based on current standings: rank1&rank3 vs rank2&rank4 per court.
export function generateAmericanoNextRound(
  tournamentId: string,
  roundNumber: number,
  existingMatches: Match[],
  players: Player[]
): Omit<Match, 'id' | 'player1' | 'player2' | 'player3' | 'player4'>[] {
  const standings = computeAmericanoStandings(existingMatches, players)
  const ranked = standings.map(s => s.player)
  return pairAmericanoRound(tournamentId, roundNumber, ranked)
}

function pairAmericanoRound(
  tournamentId: string,
  round: number,
  ranked: Player[]
): Omit<Match, 'id' | 'player1' | 'player2' | 'player3' | 'player4'>[] {
  const courts = Math.floor(ranked.length / 4)
  const matches: Omit<Match, 'id' | 'player1' | 'player2' | 'player3' | 'player4'>[] = []
  for (let c = 0; c < courts; c++) {
    const b = c * 4
    matches.push({
      tournament_id: tournamentId,
      round,
      position: c,
      player1_id: ranked[b].id,      // rank 1
      player2_id: ranked[b + 2].id,  // rank 3  → team 1: 1st & 3rd
      player3_id: ranked[b + 1].id,  // rank 2
      player4_id: ranked[b + 3].id,  // rank 4  → team 2: 2nd & 4th
      score1: null,
      score2: null,
      winner_id: null,
      status: 'pending',
    })
  }
  return matches
}

export function computeStandings(matches: Match[], players: Player[]) {
  const stats: Record<string, { wins: number; losses: number; points: number }> = {}
  for (const p of players) {
    stats[p.id] = { wins: 0, losses: 0, points: 0 }
  }
  for (const m of matches) {
    if (m.status !== 'completed' || !m.winner_id) continue
    const loserId = m.player1_id === m.winner_id ? m.player2_id : m.player1_id
    if (stats[m.winner_id]) {
      stats[m.winner_id].wins++
      stats[m.winner_id].points += 2
    }
    if (loserId && stats[loserId]) {
      stats[loserId].losses++
    }
  }
  return players
    .map(p => ({ player: p, ...stats[p.id] }))
    .sort((a, b) => b.points - a.points || b.wins - a.wins)
}

export function computePodium(
  format: 'single_elimination' | 'round_robin' | 'americano',
  matches: Match[],
  players: Player[]
): { place: number; name: string }[] {
  if (format === 'single_elimination') {
    const finalMatch = matches
      .filter(m => m.status === 'completed' && m.winner_id)
      .sort((a, b) => b.round - a.round)[0]
    if (!finalMatch) return []
    const first = players.find(p => p.id === finalMatch.winner_id)
    const secondId = finalMatch.player1_id === finalMatch.winner_id ? finalMatch.player2_id : finalMatch.player1_id
    const second = players.find(p => p.id === secondId)
    return [
      first ? { place: 1, name: first.name } : null,
      second ? { place: 2, name: second.name } : null,
    ].filter(Boolean) as { place: number; name: string }[]
  }
  const standings = format === 'round_robin'
    ? computeStandings(matches, players)
    : computeAmericanoStandings(matches, players)
  return standings.slice(0, 3).map((row, i) => ({ place: i + 1, name: row.player.name }))
}

export function computeAmericanoStandings(matches: Match[], players: Player[]) {
  const stats: Record<string, { gamesPlayed: number; points: number }> = {}
  for (const p of players) {
    stats[p.id] = { gamesPlayed: 0, points: 0 }
  }
  for (const m of matches) {
    if (m.status !== 'completed') continue
    const team1 = [m.player1_id, m.player2_id].filter(Boolean) as string[]
    const team2 = [m.player3_id, m.player4_id].filter(Boolean) as string[]
    for (const pid of team1) {
      if (stats[pid]) { stats[pid].points += m.score1 ?? 0; stats[pid].gamesPlayed++ }
    }
    for (const pid of team2) {
      if (stats[pid]) { stats[pid].points += m.score2 ?? 0; stats[pid].gamesPlayed++ }
    }
  }
  return players
    .map(p => ({ player: p, ...stats[p.id] }))
    .sort((a, b) => b.points - a.points)
}

export function americanoTotalRounds(playerCount: number): number {
  return playerCount - 1
}
